version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Prueba123
      - MSSQL_PID=Express
      - MSSQL_USER=reyk
      - MSSQL_PASSWORD=Prueba123
    ports:
      - "1434:1433"  # Asigna el puerto 1434 de tu máquina local al puerto 1433 del contenedor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
